### ISSUE TITLE
Using benchdnn test cuda failed.

### ISSUE THREAD

**Issue by malixian** [oneapi-src/oneDNN#919]
I build oneDNN on branch dev-v2 to test oneDNN example with Nvidia GPU. 
I find the ask, which said conv not support Nvidia but you can run benchdnn with Nvidia GPU？
I try to run benchdnn but I get error like this:
run command: "**./benchdnn --conv --cfg=f32 --dir=FWD_B --batch=inputs/conv/test_conv_al**l"

result is : "**error [engine_t::engine_t(dnnl_engine_kind_t):1231]: 'dnnl_engine_create(&inst, engine_kind, 0)' -> invalid_arguments(2**)"
How can I run benchdnn with Nvidia GPU? thx very much.

**Comment by malixian** [comment]
thx @dzarukin，can you tell me how to verify the cuda time is available? I try to run **"./benchdnn --softmax --engine=gpu --batch=inputs/softmax/test_softmax_ci"** to verify the cuda time, but I also have a response like this:
**"error [engine_t::engine_t(dnnl_engine_kind_t):1235]: 'dnnl_engine_create(&inst, engine_kind, 0)' -> invalid_arguments(2)
"**

**Comment by dzarukin** [comment]
Hi @malixian.

Here is the proper [link](https://github.com/oneapi-src/oneDNN/blob/master/src/gpu/nvidia/README.md). The old one was not updated yet on github by that time. Sorry about that. Now the link is fixed.

Regarding the error... it may be tough to identify the real reason and may require several debug steps to find the cause. Let's start with sourcing the compiler env and else additional env you may use, and then call ` LB_DEBUG=libs clinfo` command instead of `benchdnn`.
Something like:
~~~sh
(export comp_path=/path/to/compiler; source $comp_path/setvars.sh; LD_DEBUG=libs clinfo)
~~~

Since the output may be big, I would appreciate if you could put it into the file, please. The expected behavior is `clinfo` identifies 2 platforms - one for CPU and other for GPU. If there is only one, depending on which one is not there, the cause may be different.

Thanks.

**Comment by malixian** [comment]
thx @dzarukin, Is there any way to run the Op in CUDA runtime? I have sucessfully build oneDNN with Nvidia vendor, and I can  build and run a simple kernel successfully in Cuda runtime by using flag **"-fsycl-targets=nvptx64-nvidia-cuda-sycldevic"** .  But I can find any way to test DNN op in cuda runtime, even in the fixed [README ](https://github.com/oneapi-src/oneDNN/blob/master/src/gpu/nvidia/README.md).

**Comment by dzarukin** [comment]
Hi @malixian, I'm sorry, but I'm not following the question...

To make oneDNN work with Nvidia backend, CPU and GPU platforms should be "seen" by the system. CPU part is responsible for memory management since Unified Shared Memory (USM) is not supported for Nvidia. That's why OpenCL as an engine for GPU part should be able to discover both CPU and GPU. Based on the previous reply, something goes wrong with one or both platforms. That's why for further assistance I asked an output from `clinfo` command.

The difference between a simple kernel and oneDNN is that oneDNN also brings CPU part of the library built for TBB threading and Nvidia besides cuda also uses OpenCL implementations from OpenCL backend for Intel GPU. All three pieces are tied together and any mistake in any part will result in inability to run the library.

Thanks.

**Comment by malixian** [comment]
thx，I will continue to follow up on this issue

**Comment by malixian** [comment]
@dzarukin , I build llvm and oneDNN from source code for supporting cuda backend and I can't find file setvars.sh. But I can find this file in /opt/intel/oneapi which was installed by official installer. Maybe the file setvars.sh in the path /opt/intel/oneapi can't be right, becasue this folder was't build by cuda backend. So how can I use` clinfo` command?

**Comment by dzarukin** [comment]
Hi @malixian, I'm sorry, I was deluded `clinfo` binary is a part of standard OpenCL distribution. It appeared it's not, but this is a standard package which can be easily installed on a system via `sudo apt-get install clinfo`. Here is the most relevant link I may share with you for reference: http://manpages.ubuntu.com/manpages/bionic/man1/clinfo.1.html. Once installed, I should appear in system path automatically.

Regarding env script - it's fine to run the one from `/opt/intel/oneapi`, this is just the way it's distributed. It should source all relevant paths to compiler binaries and library path from proper linking and runtime.

BTW, even though there's no debug output yet, I may assume that there's a problem with TBB version. The thing is that compiler expects the latest TBB (https://github.com/oneapi-src/oneTBB/tree/onetbb_2021) but the opensource compiler package seems haven't updated version in a bundle which causes an issue of OpenCL can't find a CPU platform. Running the debug clinfo command will likely prove that (lack of CPU platform). In such case, I would recommend to use latest TBB by setting proper env to it and try to run oneDNN again.

If this doesn't help/work, please send me an output of `LD_DEBUG=libs clinfo` command. Thanks.

**Comment by malixian** [comment]
Thank you for your reply @dzarukin , I try to build oneTBB but also get the same failed log. 
 I can't find a description about the relationship of oneDNN and oneTBB in oneDNN work with Nvidia backend doc and don't know how to set env for TBB.  There is an output of` LD_DEBUG=libs clinfo` command.
[clinfo.log](https://github.com/oneapi-src/oneDNN/files/5706818/clinfo.log)

**Comment by dzarukin** [comment]
Hi @malixian, any luck with resolving the issue?

**Comment by malixian** [comment]
> Hi @malixian, any luck with resolving the issue?

Sorry, this problem is still not solved. Is it necessary to add some documentation or examples for explaining how to run oneDNN job with Nvidia GPU backend？

**Comment by dzarukin** [comment]
Hi @malixian, my hope you still have a desire to run this configuration. I have prepared (hopefully) full instruction step-by-step how to run cuda backend with oneDNN. Little spoiler: "no one said it would be easy no one said it would be so hard..." (c).

First, this is [an instruction from compiler side](https://intel.github.io/llvm-docs/GetStartedGuide.html#build-dpc-toolchain-with-support-for-nvidia-cuda), which I will follow in some sense. My recommendation is to read it to get the idea what's done below. When get to "Use DPC++ toolchain" step, we will use "Install low level runtime" step.

So, step-by-step (bash shell script):
```
# Install cuda 10.2
## ... will skip this step

# Install OpenCL
## ... will skip this step

# Install ninja
## ... will skip this step

# Build dpcpp compiler
git clone https://github.com/intel/llvm.git intel-llvm
export DPCPPCOMPROOT=/path/to/intel-llvm
pushd intel-llvm
## Use a sub-shell to keep env clean
(python3 $DPCPPCOMPROOT/buildbot/configure.py -s $DPCPPCOMPROOT -o $DPCPPCOMPROOT/build -t release --cuda --shared-libs --no-werror; python3 $DPCPPCOMPROOT/buildbot/compile.py -s $DPCPPCOMPROOT/llvm -o $DPCPPCOMPROOT/build)
export DPCPPCOMP=$DPCPPCOMPROOT/build

# A required for oneDNN hack to get proper OpenCL headers compatible with DPCPP.
## Explanation: compiler should use internal path to OpenCL headers. The problem is
## Nvidia ships cuda with its own OpenCL which is outdated and incompatible with DPCPP
## but is taken first due to explicit include path for cuda libs required for proper
## compilation of cuda codes in oneDNN. To be fixed in oneDNN one day.
pushd build/include
ln -s sycl/CL CL
popd

popd # from intel-llvm

# TBB
## Download package https://github.com/oneapi-src/oneTBB/releases/download/v2021.1.1/oneapi-tbb-2021.1.1-lin.tgz
## Untar with gzip
## Side comment about TBB: though oneDNN doesn't hard require TBB and will build
## with sequential runtime, currently oneDNN does not produce any test binaries which
## don't depend on CPU engine (both gtests and benchdnn rely on it). But in theory,
## TBB is not needed in a scenario when only GPU engine is used to run oneDNN
## primitives on Nvidia GPU. Though it's hard to imagine a proper work with memory
## (like results validation and other) without CPU engine.

# OpenCL CPU Runtime
## Download package https://github.com/intel/llvm/releases/download/2020-12/oclcpuexp-2020.11.11.0.04_rel.tar.gz
## Untar with gzip
## Move the content to "intelocl" folder
echo libintelocl.so > /etc/OpenCL/vendors/intel-cpu.icd

# Setting environment
export PATH=$DPCPPCOMP/bin:$PATH
export CPATH=$DPCPPCOMP/include:$CPATH
export LIBRARY_PATH=$DPCPPCOMP/lib:$LIBRARY_PATH
export LD_LIBRARY_PATH=$DPCPPCOMP/lib:$LD_LIBRARY_PATH
export OCL_ICD_FILENAMES="path/to/intelocl/x64/libintelocl.so"
source /path/to/oneapi-tbb-2021.1.1/env/vars.sh

# Build oneDNN with Nvidia backend
git clone https://github.com/oneapi-src/oneDNN.git
pushd oneDNN
## Separate shell to keep env clean
(mkdir -p build; pushd build; cmake -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_INSTALL_PREFIX=build -DDNNL_LIBRARY_TYPE=SHARED -DCMAKE_BUILD_TYPE=release -DDNNL_CPU_RUNTIME=DPCPP -DDNNL_GPU_RUNTIME=DPCPP -DDNNL_SYCL_CUDA=ON -DDNNL_GPU_VENDOR=NVIDIA -DOPENCLROOT=$DPCPPCOMP ..; ninja all)

# Run benchdnn (follow benchdnn documentation to run different primitives)
$ DNNL_VERBOSE=1 ./build/tests/benchdnn/benchdnn --engine=gpu --binary 3x4x5:3x4x5
dnnl_verbose,info,oneDNN v2.0.0 (commit XXX)
dnnl_verbose,info,cpu,runtime:DPC++
dnnl_verbose,info,cpu,isa:Intel AVX-512 with AVX512BW, AVX512VL, and AVX512DQ extensions
dnnl_verbose,info,gpu,runtime:DPC++
dnnl_verbose,info,cpu,engine,0,backend:OpenCL,name:Intel(R) Core(TM) i9-7920X CPU @ 2.90GHz,driver_version:2020.11.11
dnnl_verbose,info,gpu,engine,0,backend:Nvidia,name:TITAN RTX,driver_version:0.0.0
dnnl_verbose,info,prim_template:operation,engine,primitive,implementation,prop_kind,memory_descriptors,attributes,auxiliary,problem_desc,exec_time
dnnl_verbose,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:abc:f0 dst_f32::blocked:abc:f0,,,3x4x5,0.137939
dnnl_verbose,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:abc:f0 dst_f32::blocked:abc:f0,,,3x4x5,0.0629883
dnnl_verbose,exec,gpu,binary,**cuda:cudnn:any**,undef,src_f32::blocked:abc:f0 src_f32::blocked:abc:f0 dst_f32::blocked:abc:f0,,alg:binary_add,3x4x5:3x4x5,0.189941
dnnl_verbose,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:abc:f0 dst_f32::blocked:abc:f0,,,3x4x5,0.0620117
0:PASSED __REPRO: --binary --engine=gpu 3x4x5:3x4x5
tests:1 passed:1 skipped:0 mistrusted:0 unimplemented:0 failed:0 listed:0
``` 

Phew... I hope not to forget anything. If something doesn't work, please let me know, I will update it accordingly. Thank you for your patience.

**Comment by malixian** [comment]
@dzarukin Thanks for your guidance，I will try it.

**Comment by Dr-Noob** [comment]
I'm having the same issue. I built oneDNN to test benchdnn with CUDA, but it does not even work with CPU...

```
[drnoob@xeon benchdnn]$ export SYCL_HOME=~/sycl_workspace
[drnoob@xeon benchdnn]$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$SYCL_HOME/llvm/build/lib
[drnoob@xeon benchdnn]$ ./benchdnn --conv --cfg=f32 --dir=FWD_B --batch=inputs/conv/test_conv_ci
error [engine_t::engine_t(dnnl_engine_kind_t):1261]: 'dnnl_engine_create(&inst, engine_kind, idx)' -> invalid_arguments(2)
```

I don't understand why the error message is just "invalid_arguments". This does not help to solve the problem at all because it does not give us any information about what's wrong in our setup.

**Comment by Dr-Noob** [comment]
@dzarukin  I think our issue is related to the warning: 

```
runtime library [libOpenCL.so.1] in /home/user/sycl_workspace/build/lib may be hidden by files in:
      /usr/local/cuda-10.2/targets/x86_64-linux/lib
```

because @malixian shows this message in the cmake output, and I noticed the same, even tough I did the trick you mention by doing `ln -s sycl/CL CL`. I will try to fix the issue, because it looks like we built oneDNN with the CUDA OpenCL headers, and that is causing this mess.

**Comment by Dr-Noob** [comment]
It looks like I managed to get it working.

I removed the wrong `libOpenCL.so.1` (ugly but safe trick since it just a symlink). I built the lib again and now `ldd` says that benchdnn is linked against the correct library. With this, I got a little further, but the error appeared anyway.

After that, I followed the instructions @dzarukin provided. Specifically, what I was doing different was:
- My build was linking agains TBB in the oneapi I had installed (`/opt/intel/compilers_and_libraries_2020.2.254/linux/tbb`). I downloaded TBB from the link that @dzarukin posted and linked against this tbb version using `-DTBBROOT`
- I did not source the script at `/path/to/oneapi-tbb-2021.1.1/env/vars.sh`. I fixed this too (without the source, it failed in the linking process). But I did not source the script at the TBB I downloaded, but at the oneapi I had installed systemwide (`/opt/intel/oneapi/setvars.sh`). Really strange...

And it finally works:

```
[drnoob@xeon build]$ DNNL_VERBOSE=1 ./tests/benchdnn/benchdnn --engine=gpu --binary 3x4x5:3x4x5
dnnl_verbose,info,oneDNN v2.0.0 (commit 8d623ef7a6ff4f188079725700a963fc24922527)
dnnl_verbose,info,cpu,runtime:DPC++
dnnl_verbose,info,cpu,isa:Intel AVX-512 with Intel DL Boost
dnnl_verbose,info,gpu,runtime:DPC++
dnnl_verbose,info,cpu,engine,0,backend:OpenCL,name:mycpu
dnnl_verbose,info,gpu,engine,0,backend:Nvidia,name:mygpu
dnnl_verbose,info,prim_template:operation,engine,primitive,implementation,prop_kind,memory_descriptors,attributes,auxiliary,problem_desc,exec_time
dnnl_verbose,exec,cpu:0,reorder,jit:uni,undef,src_f32::blocked:abc:f0 dst_f32::blocked:abc:f0,,,3x4x5,0.170898
dnnl_verbose,exec,cpu:0,reorder,jit:uni,undef,src_f32::blocked:abc:f0 dst_f32::blocked:abc:f0,,,3x4x5,0.0129395
dnnl_verbose,exec,gpu:0,binary,cuda:cudnn:any,undef,src_f32::blocked:abc:f0 src_f32::blocked:abc:f0 dst_f32::blocked:abc:f0,,alg:binary_add,3x4x5:3x4x5,0.251953
dnnl_verbose,exec,cpu:0,reorder,jit:uni,undef,src_f32::blocked:abc:f0 dst_f32::blocked:abc:f0,,,3x4x5,0.0129395
0:PASSED __REPRO: --binary --engine=gpu 3x4x5:3x4x5
tests:1 passed:1 skipped:0 mistrusted:0 unimplemented:0 failed:0 listed:0
```

@malixian I hope you find this useful!

**Comment by malixian** [comment]
@Dr-Noob  I think it not the problem about the warning of libOpenCl path, because we can specify the path of opencl by `-DOPENCLROOT=/usr/local/cuda-10.2/targets/x86_64-linux/lib/` and there is no warning.
But I also can't test benchdnn with CUDA although recompile the oneDNN. 
What inspired me is `source /opt/intel/oneapi/setvars.sh` may work.
@dzarukin It's only need setting environment by command `source /path/to/oneapi-tbb-2021.1.1/env/vars.sh`?, I think ` /opt/intel/oneapi/setvars.sh` helps @Dr-Noob run successfully.

**Comment by dzarukin** [comment]
Hi @malixian, sorry for a lame question - have you tried 2021.1 TBB version? It looks like the old one is still used unless path `DTBBROOT=$SYCL_HOME/oneTBB/` contains updated bits. Something tells me the problem in TBB used, not in any other place.
To become absolutely sure, please try to run benchdnn with `--engine=cpu`. If it's not working, the problem is 100% in TBB library used.

**Comment by igorsafo** [comment]
Hi @malixian , could you try to run benchdnn under strace?
DPC++ RT loads compiler libraries at runtime and if one of dependencies is not there it fails. Strace could help to identify such issue: https://github.com/intel/llvm/issues/624

**Comment by ucasgx** [comment]
Hi @dzarukin, I followed your  instructions and used 2021.1 TBB, but I still cannot run the benchdnn on cpu, and got the same error [engine_t::engine_t(dnnl_engine_kind_t):1254]: 'dnnl_engine_create(&inst, engine_kind, 0)' -> invalid_arguments(2). 
It looks like the tbb problem but I don't know why:

```
getpid()                                = 2149159
stat("/proc/2149159/ns/pid", {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
stat("/proc/2149159/ns/pid", {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
socket(AF_UNIX, SOCK_SEQPACKET|SOCK_CLOEXEC, 0) = 11
unlink("")                              = -1 ENOENT (No such file or directory)
bind(11, {sa_family=AF_UNIX, sun_path=@"cuda-uvmfd-4026531836-2149159\0"}, 33) = 0
listen(11, 128)                         = 0
mmap(NULL, 8392704, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7f3e95841000
mprotect(0x7f3e95842000, 8388608, PROT_READ|PROT_WRITE) = 0
clone(child_stack=0x7f3e9603b8f0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tid=[2149169], tls=0x7f3e96041000, child_tidptr=0x7f3e960412d0) = 2149169
getpid()                                = 2149159
futex(0x7f3e9c0b8da8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
fstat(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(0x88, 0x2), ...}) = 0
write(1, "error [engine_t::engine_t(dnnl_e"..., 123error [engine_t::engine_t(dnnl_engine_kind_t):1267]: 'dnnl_engine_create(&inst, engine_kind, idx)' -> invalid_arguments(2)
) = 123
exit_group(2)                           = ?
+++ exited with 2 +++
```

**Comment by dzarukin** [comment]
Hi @ucasgx, thank you for your report.

I'm sorry this is confusing and that neither the library nor benchdnn binary doesn't give a hint what is wrong. We are planning to improve it, but it will take some time.

So far, I may suggest you couple things to verify:
1) Under same env benchdnn is run, please run `clinfo` to check whether CPU platform is there.
2) Try to run `strace benchdnn ... > log.file 2>&1`. This may also give a hint what's wrong. It may happen that some library was not found by any reason. It's likely to show whether TBB is involved or not.

I'm also going to write sort of debug instructions that it's easier to identify and fix the problem if it's something on user's side. Sorry for inconveniences.

**Comment by ucasgx** [comment]
Hi @dzarukin ,thank you for your answer.
I upgrade my openCL version and now it worked.
